const buttons=[
    {name:"Height",
     property:"height",
     min:0,
     max:400,
     unit:"px"
    },
     {name:"Width",
     property:"width",
     min:0,
     max:400,
     unit:"px"
    },
     {name:"Border",
     property:"border-radius",
     min:0,
     max:50,
     unit:"%"
    },
    {name:"Blur",
  property:"blur",
  min:0,
  max:10,
  unit:"px"
 },
 {name:"Hue-Rotate",
 property:"hue-rotate",
 min:0,
 max:100,
 unit:"deg"
},
     {name:"Sepia",
     property:"sepia",
     min:0,
     max:100,
     unit:"%"
    },
    {name:"GrayScale",
     property:"grayscale",
     min:0,
     max:100,
     unit:"%"
    },
    {name:"Contrast",
    property:"contrast",
    min:0,
    max:100,
    unit:"%"
   },
   {name:"Saturate",
   property:"saturate",
   min:0,
   max:100,
   unit:"%"
  },
  
]